### ISSUE TITLE
How to use async method inside a task?

### ISSUE THREAD

**Issue by FredJul** [GlebBatykov/ossa#1]
I have plugin methods I would like to start in a separated isolate and wanted to use ossa for this since the API is way better than  standard isolate one. However the following code does not seems to work:
```
void main() async {
  // Create and run Task using run method
  var task = await Task.run((context) async {
    await futureMethod();
  });

  // Wait when task is completed
  await task.result();
}
```

Is there any way to bypass this?

**Comment by GlebBatykov** [comment]
Hi, by 'plugin methods' you mean calling something with PlatformChannels in Flutter?

If that's what you mean, then there are some problems with that.

As far as I know, the isolates running in the Flutter application do not have access to PlatformsChannels, because, unlike our main isolate, FlutterEngine does not run in them. And therefore, as far as I know, there is a 'flutter_isolate' package.

If this is the problem, then I could release an update for this package allowing the use of PlatformChannels.

**Comment by GlebBatykov** [comment]
Oops, there is such a problem without PlatformChannels or something like that.

I have already fixed it, I will update the package now.

**Comment by GlebBatykov** [comment]
I have updated the package. Try using the package version 1.0.3.

**Comment by FredJul** [comment]
Well, I believe that being able to use an async method can be good, even without any PlatformChannels. But yes, in my case I would need to call methods from a platform channel so I may encounter issues like you said. I'll investigate.

But in all cases, thank you for your responsiveness and congratulation for this very useful package!

**Comment by FredJul** [comment]
I just tried the 1.0.3 version and yes, I now had the issue related to the PlatformChannels as you said. I however consider this issue to be fixed, and will check flutter_isolate.
